<?php

/**
 * Все методы будут идти через POST
 * Request
 * {
"method": "GetPosts", // вызываемый метод
"param": {
"page": {}, // настройки пагинации
"include": {}, // настройки связей
"fields": {}, // необходимые атребуты
"filters": {}, // настройки фильтраци
"sort": {}, // настройки сортировки
},
"token": "000000000000", // токен авторизации
"version": "1" // версия API
 * }
 */

/**
 * // настройки пагинации
 * ?page = [
 *      'size' => 30 // количество нововтей на стронице
 *      'number' => 2 // номер страницы из пагинации
 *      'published_at' => 1538332156 // курсорная паджинация
 * ]
 *
 * // необходимые связи для главного объекта
 * ?relation = category,seller,user // Ссылки на них будут в разделе $response[data][relationships]
 *
 * // список необходимых атрибутов каждой сущности к возвращению
 * ?fields = [
 *      article => title, name, description
 *      category => alias, name
 *      seller => id, name, status
 * ]
 *
 * // параметр для поиска и фильтрации
 * ?filters = [
 *       search => text for search // поиск по тексту
 *       from_date => 1538332156 // загрузить статьи с определенной даты
 *       is_published => true // загрузить статьи, которые только опубликованы
 *       author => 2 // загрузить статьи со вторым автором
 * ]
 *
 * // сортировка статей
 * ?sort = author,-publisbed_at // сначала по автору, потом по дате публикации в обратном направлении, если статьи у одного автора
 * ?sort = published_at // по дате публикации
 *
 */

/**
 * Response
 * {
"data": {
[
"type": "posts" // тип сущности
"id": 12 // идентификатор
"attributes": {} // атрибуты сущности
"relationships": {} // ссылки на зависимости
]
}
"included": {} // список объектов сущностей из зависимостей
"errors": {} // список объектов ошибки
 * }
 */

abstract class Controller_Json_Api extends Controller {


    protected $_request; // объект запроса
    protected $_response; // объект ответа

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub

        // если пришел запрос с корректным HEADER
        if($this->request->is_ajax()){
            $data = (array)$this->request->post();
        } else { // в противном случае. KOHANA через внутренний реквест не может корректно отправить запрос с выставление заголовка. Возможно решиться при отправке по реальному доменному имени.
            $data = (array)json_decode($this->request->body(), true);
        }

        $this->_request = new Json_Api_Request($data);
        $this->_response = new Json_Api_Response();
    }

    public function after()
    {
        $this->response->headers('Content-Type', 'application/json; charset=utf-8');
        $this->response->body(
            json_encode(
                $this->_response->execute()
            )
        );

        parent::after(); // TODO: Change the autogenerated stub
    }
}
